### ISSUE TITLE
ABY inner product AMI: volume size

### ISSUE THREAD

**Issue by lenerd** [cryptobiu/MATRIX#14]
Hi,
I cannot deploy instances for the ABY inner product protocol since the disk is too small (see below for a traceback). In `deploy_instances()` the disk image is fixed to a size of 20 G:
https://github.com/cryptobiu/MATRIX/blob/92cc27b504d4e7fa48dedfe0194e2633b375bc8e/Deployment/aws_deploy.py#L144 The error message says that the snapshot for the AMI needs at least 100 G. Is an image that big necessary?
```
Welcome to MATRIX system.
Please Insert your choice:
1. Deploy Menu
2. Execute Menu
3. Analysis Menu
4. Generate Circuits
5. Exit
Your choice:1
Enter configuration file(s):
Configuration file path (current path is: /path/to/MATRIX): ProtocolsConfigurations/Config_ABY_InnerProduct.json
Choose cloud provider:
1. AWS
2. Scaleway
Your choice:1
Choose deployment task
1. Deploy Instance(s)
2. Create Key pair(s)
3. Create security group(s)
4. Get instances network data
5. Terminate machines
6. Change machines types
7. Start instances 
8. Stop instances
Your choice:1
Current date : 
2018-09-16 08:31:13.071261
Deploying instances :
region : us-east-1b
number of instances : 2
ami_id : ami-08c9a677
instance_type : c5.large
valid until : 2018-09-16 14:31:13.071261
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    main()
  File "main.py", line 159, in main
    print_instances_management_menu(conf_file_path)
  File "main.py", line 54, in print_instances_management_menu
    deploy.deploy_instances()
  File "/path/to/MATRIX/Deployment/aws_deploy.py", line 167, in deploy_instances
    'Value': protocol_name
  File "/path/to/MATRIX/.venv/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/path/to/MATRIX/.venv/lib/python3.7/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Volume of size 20GB is smaller than  snapshot 'snap-0cfcf1ed8aca9f22e', expect size >= 100GB
```

**Comment by liorko87** [comment]
Hi,

The disk size determined by the AMI. No need to specify it.
