### ISSUE TITLE
Configuration cannot include equals sign

### ISSUE THREAD

**Issue by GuutBoy** [cryptobiu/MATRIX#42]
MATRIX fails when the arguments given in the `configurations` section of the MATRIX config file includes an equals sign. 

Example:

Using the following config
```
{
  "protocol":"FRESCO-SPDZ",
  "CloudProviders":
  {
    "local":
    {
      "numOfParties":2,
      "git":
      {
        "gitBranch": ["matrix-framework-test"],
        "gitAddress": ["https://github.com/aicis/fresco.git"]
      }
    }
  },
  "executableName": ["MATRIX/run.sh"],
  "configurations":
  [
    "-e@SEQUENTIAL_BATCHED@-s@spdz@-Dspdz.preprocessingStrategy=DUMMY"
  ],
  "numOfRepetitions":1,
  "numOfInternalRepetitions":1,
  "IsPublished": "true",
  "isExternal": "true",
  "workingDirectory": ["~/MATRIX-EXP/fresco-test"],
  "resultsDirectory": "~/MATRIX-EXP/MATRIX",
  "emails": ["peter.s.nordholt@alexandra.dk"],
  "institute":"The Alexandra Institute"
}
```
I get the following error when trying to execute the experiment
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/psn/Library/Python/2.7/lib/python/site-packages/fabric/tasks.py", line 242, in inner
    submit(task.run(*args, **kwargs))
  File "/Users/psn/Library/Python/2.7/lib/python/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
TypeError: run_protocol() got an unexpected keyword argument '-e@SEQUENTIAL_BATCHED@-s@spdz@-Dspdz.preprocessingStrategy'
```
Looks like some issue with the configurations strings not being properly handled.

**Comment by GuutBoy** [comment]
For now I am dealing with it by using `%` instead of `=` and then substituting back in the `run.sh` script. Not pretty, but it seems to work. Would be great to have this fixed though. In the long run banning `=` from the configurations does not seem sustainable.

**Comment by liorko87** [comment]
#38
